### ISSUE TITLE
Training it on a new language

### ISSUE THREAD

**Issue by mathigatti** [aparrish/pincelate#11]
Hi! Amazing project, thanks for sharing :)

I would like to train it with Spanish words. Do you have for any chance an example or short guide about how to run the training script and how the training data should look like?

**Comment by aparrish** [comment]
[Instructions on running the training script are part of the documentation](https://pincelate.readthedocs.io/en/latest/training.html). To adapt the model to a different language, you'd need a phonetic dictionary for that language, and a mapping of each phoneme to its phonetic features. The files [`cmudictdata.py`](https://github.com/aparrish/pincelate/blob/main/pincelate/cmudictdata.py) and [`featurephone.py`](https://github.com/aparrish/pincelate/blob/main/pincelate/featurephone.py) show how I load data from the CMU Pronouncing Dictionary and associate the arpabet phonemes with phonetic features for English. There is [a little bit of code in the main `Pincelate` class](https://github.com/aparrish/pincelate/blob/main/pincelate/__init__.py#L46-L62) that deals directly with the arpabet representation of phonemes, in order to make it easier to return a string of phonemes instead of an array of phoneme features—you'd probably need to adapt this for the phonetic representation of the language in question. I used [Kirshenbaum's scheme](https://web.archive.org/web/20160304092234/http://www.kirshenbaum.net/IPA/ascii-ipa.pdf) for representing phonetic features, but in the future I'd probably use a scheme like that in [PHOIBLE](https://phoible.org/) with an eye toward making a model that works cross-linguistically.

Hope this helps!

**Comment by mathigatti** [comment]
Thank you very much!
